title: This is my test github page!!!!
author: Steven Farkas
email: farkas.stev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is just a test description so that I can learn more about Github pages and 
  continue to get practice using Github overall. I will mst likely actually use 
  GitHub pages at a later date to host a personal website.

# social links
twitter_username: thefurthestkas # DO NOT include the @ character, or else the build will fail!
github_username:  FarkasStev # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
